# Generated by Django 5.2.5 on 2025-08-18 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReasonPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_id', models.IntegerField()),
                ('confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=16)),
                ('explanation', models.TextField()),
                ('product_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='reviews.productprediction')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('summary_notes', models.TextField(blank=True)),
                ('product_prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.productprediction')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('confirmed', 'Confirmed'), ('overridden', 'Overridden')], max_length=16)),
                ('corrected_explanation', models.TextField(blank=True)),
                ('reason_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.rejectionreasonprediction')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='reviews.review')),
            ],
        ),
    ]
